COMPILER = gcc
LANGUAGE = -x c
DEBUG_MODE = -g 
BINARY = -o ./BINARIES/EXECUTIVE
CODEFILES = ./CODEFILES/main.c ./CODEFILES/ANIM/anim.c ./CODEFILES/ANIM/UNITS/unit.c ./CODEFILES/RENDER/render.c ./CODEFILES/RENDER/SHADERS/shader.c ./CODEFILES/ANIM/CONTROLLER/controller.c ./CODEFILES/ANIM/IMAGES/images.c ./CODEFILES/ANIM/TEXTURES/textures.c ./CODEFILES/ANIM/UNITS/QUAD_ROTATING/quad.c ./CODEFILES/ANIM/UNITS/OS/os.c ./CODEFILES/ANIM/UNITS/3DCUBE/3dcube.c
CFLAGS = `sdl2-config --libs --cflags` -ggdb3 -O0 --std=c99 -Wall -lGL -lGLU -lSDL2_image -lm 

all:
	@$(COMPILER) $(LANGUAGE) $(DEBUG_MODE) $(BINARY) $(CODEFILES) $(CFLAGS) 

