COMPILER 		   = gcc

LANGUAGE 		   = -x c

DEBUG_MODE 		   = -g 

BINARY 			   = -o ./BINARIES/EXECUTIVE

MAIN_SUBSYSTEM 	   = ./CODEFILES/main.c
ANIM_SUBSYSTEM 	   = ./CODEFILES/ANIM/anim.c ./CODEFILES/ANIM/UNITS/unit.c ./CODEFILES/ANIM/TOPOLOGY/topology.c ./CODEFILES/ANIM/CONTROLLER/controller.c
SCANNER_SUBSYSTEM  = ./CODEFILES/SCANNER/scanner.c
RENDER_SUBSYSTEM   = ./CODEFILES/RENDER/render.c ./CODEFILES/RENDER/SHADERS/shader.c ./CODEFILES/RENDER/PRIMITIVES/primitives.c \
					 ./CODEFILES/RENDER/IMAGES/images.c ./CODEFILES/RENDER/TEXTURES/textures.c ./CODEFILES/RENDER/MATERIALS/materials.c 

QUAD_UNIT          = ./CODEFILES/ANIM/UNITS/QUAD_ROTATING/quad.c
OS_UNIT            = ./CODEFILES/ANIM/UNITS/OS/os.c
SCENE_UNIT         = ./CODEFILES/ANIM/UNITS/SCENE/scene.c ./CODEFILES/ANIM/UNITS/SCENE/CUBE/cube.c ./CODEFILES/ANIM/UNITS/SCENE/PLANE/plane.c

UNITS              = $(QUAD_UNIT) $(OS_UNIT) $(SCENE_UNIT)

CODEFILES 		   = $(MAIN_SUBSYSTEM) $(ANIM_SUBSYSTEM) $(RENDER_SUBSYSTEM) $(SCANNER_SUBSYSTEM) $(UNITS) 

CFLAGS 			   = `sdl2-config --libs --cflags` -ggdb3 -O0 --std=c99 -Wall -lGL -lGLU -lSDL2_image -lm 

all:
	@$(COMPILER) $(LANGUAGE) $(DEBUG_MODE) $(BINARY) $(CODEFILES) $(CFLAGS)

log:
	@$(COMPILER) $(LANGUAGE) $(DEBUG_MODE) $(BINARY) $(CODEFILES) $(CFLAGS) 2> log.txt

